/**
 * Text widths from metric tables, never from the canvas (review C1).
 *
 * `ctx.measureText` differs between Skia (Chrome, the render worker),
 * CoreText (Safari) and FreeType/HarfBuzz, so line breaks measured by the
 * canvas can differ per platform. The engine measures every word from
 * fonts.json instead (advances per codepoint + flattened GPOS pair
 * kerning, generated by scripts/build-caption-fonts.py) and draws each word
 * at the x it computed. Line breaks and word positions are therefore the
 * same everywhere; only anti-aliasing inside a word can differ.
 *
 * Devanagari needs shaping (conjuncts, matras): runs in a font's
 * devanagari face are measured by HarfBuzz (shape-hb.ts) once it is loaded.
 *
 * Fonts are addressed as FACES: one per font and script subset, each its
 * own CSS family ("cc-<font>-<subset>"), because the browser loads them as
 * separate files. Per-job CJK subsets (UT3) are registered at runtime with
 * registerFont() in the same JSON format.
 */
import { shapeWidth } from "./shape-hb";

export type SubsetJson = {
  family: string;
  file: string;
  bytes: number;
  sha256: string;
  unicodeRange: string;
};

export type FontJson = {
  name: string;
  weight: number;
  italic: boolean;
  unitsPerEm: number;
  ascender: number;
  descender: number;
  capHeight: number;
  xHeight: number;
  subsets: Record<string, SubsetJson>;
  /** [[firstCodepoint, advance, advance, ...], ...] in font units. */
  advances: number[][];
  kerning: { left: number[][]; right: number[][]; nRight: number; values: number[] };
  ttf?: string;
  ttfBytes?: number;
  ttfSha256?: string;
  version?: string | null;
  license?: string;
};

export type DeferredFontJson = {
  name: string;
  family: string;
  weight: number;
  lang: string;
  unitsPerEm: number;
  source: string;
  note: string;
};

export type FontTables = {
  version: number;
  baseUrl: string;
  defaultFont: string;
  fonts: Record<string, FontJson>;
  deferred: Record<string, DeferredFontJson>;
};

export type Face = {
  /** "<fontId>:<subset>" */
  key: string;
  fontId: string;
  subset: string;
  /** CSS family the face is registered under (browser FontFace / Node alias). */
  family: string;
  file: string;
  url: string;
  format: "woff2" | "truetype";
  unicodeRange: string;
  cps: ReadonlySet<number>;
  metrics: FontMetrics;
};

function expandRuns(rows: number[][]): Map<number, number> {
  const out = new Map<number, number>();
  for (const row of rows) for (let i = 1; i < row.length; i++) out.set(row[0] + i - 1, row[i]);
  return out;
}

export function parseUnicodeRange(spec: string): Set<number> {
  const out = new Set<number>();
  for (const part of spec.split(",")) {
    const m = /^U\+([0-9A-F]+)(?:-([0-9A-F]+))?$/i.exec(part.trim());
    if (!m) continue;
    const a = parseInt(m[1], 16);
    const b = m[2] ? parseInt(m[2], 16) : a;
    for (let cp = a; cp <= b; cp++) out.add(cp);
  }
  return out;
}

export class FontMetrics {
  readonly id: string;
  readonly name: string;
  readonly upm: number;
  readonly ascender: number;
  readonly descender: number;
  readonly capHeight: number;
  readonly xHeight: number;
  readonly faces: Face[];
  private readonly adv: Map<number, number>;
  private readonly kernLeft: Map<number, number>;
  private readonly kernRight: Map<number, number>;
  private readonly nRight: number;
  private readonly kernValues: number[];

  constructor(id: string, json: FontJson, baseUrl: string) {
    this.id = id;
    this.name = json.name;
    this.upm = json.unitsPerEm;
    this.ascender = json.ascender;
    this.descender = json.descender;
    this.capHeight = json.capHeight;
    this.xHeight = json.xHeight;
    this.adv = expandRuns(json.advances);
    this.kernLeft = expandRuns(json.kerning.left);
    this.kernRight = expandRuns(json.kerning.right);
    this.nRight = json.kerning.nRight;
    this.kernValues = json.kerning.values;
    this.faces = Object.entries(json.subsets).map(([subset, s]) => ({
      key: `${id}:${subset}`,
      fontId: id,
      subset,
      family: s.family,
      file: s.file,
      url: /^(https?:|blob:|data:|\/)/.test(s.file) ? s.file : baseUrl + s.file,
      format: s.file.endsWith(".ttf") ? "truetype" : "woff2",
      unicodeRange: s.unicodeRange,
      cps: parseUnicodeRange(s.unicodeRange),
      metrics: this,
    }));
  }

  advance(cp: number): number | undefined {
    return this.adv.get(cp);
  }

  kern(a: number, b: number): number {
    const l = this.kernLeft.get(a);
    if (!l) return 0;
    const r = this.kernRight.get(b);
    if (!r) return 0;
    return this.kernValues[(l - 1) * this.nRight + (r - 1)] ?? 0;
  }

  face(subset: string): Face | undefined {
    return this.faces.find((f) => f.subset === subset);
  }
}

// ---------------------------------------------------------------- registry

let tables: FontTables | null = null;
const fonts = new Map<string, FontMetrics>();
let tablesPromise: Promise<FontTables> | null = null;

/** Registers the built-in tables (fonts.json). Idempotent. */
export function setFontTables(json: FontTables): void {
  if (tables === json) return;
  tables = json;
  for (const [id, f] of Object.entries(json.fonts)) fonts.set(id, new FontMetrics(id, f, json.baseUrl));
}

/**
 * Loads fonts.json on first use (a separate chunk: ~50 KB gzip, so it
 * stays out of the first-load JS of the pages that mount captions).
 */
export function loadFontTables(): Promise<FontTables> {
  if (tables) return Promise.resolve(tables);
  if (!tablesPromise) {
    tablesPromise = import("./fonts.json").then((mod) => {
      const json = (mod.default ?? mod) as unknown as FontTables;
      setFontTables(json);
      return json;
    });
    tablesPromise.catch(() => {
      tablesPromise = null;
    });
  }
  return tablesPromise;
}

export function fontTables(): FontTables | null {
  return tables;
}

/**
 * Registers a font at runtime, e.g. a job's CJK subset (UT3): `json` has
 * the fonts.json entry format; subset files may be absolute URLs.
 */
export function registerFont(id: string, json: FontJson, baseUrl = ""): FontMetrics {
  const m = new FontMetrics(id, json, baseUrl || tables?.baseUrl || "");
  fonts.set(id, m);
  return m;
}

export function getFont(id: string): FontMetrics | undefined {
  return fonts.get(id);
}

export function requireFont(id: string): FontMetrics {
  const f = fonts.get(id);
  if (!f) {
    throw new Error(
      tables
        ? `caption font "${id}" is not registered`
        : "caption font tables are not loaded: await ensureFonts() / loadFontTables() first",
    );
  }
  return f;
}

export function deferredFont(id: string): DeferredFontJson | undefined {
  return tables?.deferred[id];
}

// ---------------------------------------------------------------- measuring

/** Zero-width format characters: never visible, never measured. */
export function isIgnorable(cp: number): boolean {
  return (
    cp === 0x00ad ||
    (cp >= 0x200b && cp <= 0x200f) ||
    (cp >= 0x2060 && cp <= 0x2064) ||
    cp === 0xfeff ||
    (cp >= 0xfe00 && cp <= 0xfe0f) ||
    (cp >= 0x0300 && cp <= 0x036f)
  );
}

/** Estimated advance (em) of a character no face covers. */
export function fallbackAdvance(cp: number): number {
  if (isIgnorable(cp)) return 0;
  if (cp === 0x20 || cp === 0xa0) return 0.26;
  if (
    (cp >= 0x1100 && cp <= 0x11ff) ||
    (cp >= 0x2e80 && cp <= 0x9fff) ||
    (cp >= 0xac00 && cp <= 0xd7af) ||
    (cp >= 0xf900 && cp <= 0xfaff) ||
    (cp >= 0xfe30 && cp <= 0xfe4f) ||
    (cp >= 0xff00 && cp <= 0xff60) ||
    (cp >= 0x1f300 && cp <= 0x1faff) ||
    cp >= 0x20000
  ) {
    return 1;
  }
  return 0.6;
}

export type Measure = {
  em: number;
  /** Some character had no face: its width is an estimate. */
  approximate: boolean;
};

function isDevanagari(cp: number): boolean {
  return (cp >= 0x0900 && cp <= 0x097f) || (cp >= 0xa8e0 && cp <= 0xa8ff) || (cp >= 0x1cd0 && cp <= 0x1cff);
}

/**
 * Width of `text` in em when drawn with the face list `faces` (the order
 * of the CSS family list): every character takes the first face that
 * covers it, consecutive characters of one face form a run, runs are
 * kerned inside (never across) — like the browser's font fallback.
 */
export function measureText(text: string, faces: readonly Face[]): Measure {
  let em = 0;
  let approximate = false;
  let runFace: Face | null = null;
  let run = "";
  let runUnits = 0;
  let runShaped = false;
  let prev = -1;
  const flush = () => {
    if (!runFace || !run) return;
    const m = runFace.metrics;
    if (runShaped) {
      const shaped = shapeWidth(runFace.key, run);
      if (shaped !== undefined) {
        em += shaped / m.upm;
      } else {
        em += runUnits / m.upm;
        approximate = true;
      }
    } else {
      em += runUnits / m.upm;
    }
  };
  for (const ch of text) {
    const cp = ch.codePointAt(0)!;
    let face: Face | null = null;
    for (const f of faces) {
      if (f.cps.has(cp)) {
        face = f;
        break;
      }
    }
    if (!face) {
      if (!isIgnorable(cp)) approximate = true;
      em += fallbackAdvance(cp);
      prev = -1;
      continue;
    }
    if (face !== runFace) {
      flush();
      runFace = face;
      run = "";
      runUnits = 0;
      runShaped = false;
      prev = -1;
    }
    run += ch;
    if (face.subset === "devanagari" && isDevanagari(cp)) runShaped = true;
    const a = face.metrics.advance(cp) ?? 0;
    runUnits += a + (prev >= 0 ? face.metrics.kern(prev, cp) : 0);
    prev = cp;
  }
  flush();
  return { em, approximate };
}
