"""testdata/caption_units_vectors.json (UX8): the v1 caption units of a
transcription — src/audio.py _build_subtitles_from_transcription, which
glues a word of ≤ 3 characters to the next one inside a Whisper segment
and drops filler sounds — next to the edit document's words of the same
transcription (backend/doc.py words_from_transcript). The web builds its
export units from the doc words (web/src/features/editor/state/doc.ts
captionSource) and must give the same units for an unedited doc; its
vitest runs the same file. This test keeps the vectors true to both
Python sides.

Regenerate: python backend/tests/test_caption_units_vectors.py --write
"""
from __future__ import annotations

import json
import sys
import types
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
VECTORS = REPO / "testdata" / "caption_units_vectors.json"
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from backend import doc as edit_doc  # noqa: E402


def _segments(sentences: list[str], t0: float = 0.0, word_s: float = 0.32,
              pause: float = 0.6) -> list[dict]:
    """Whisper-like segments, one per sentence, words evenly timed."""
    segs, t = [], t0
    for sent in sentences:
        words = []
        for tok in sent.split():
            dur = word_s if len(tok) > 3 else word_s * 0.6
            words.append({"word": " " + tok, "start": round(t, 2), "end": round(t + dur, 2)})
            t = round(t + dur + 0.04, 2)
        segs.append({"start": words[0]["start"], "end": words[-1]["end"], "text": sent,
                     "words": words})
        t = round(t + pause, 2)
    return segs


CASES = {
    "speech script (fillers, short words)": [
        "Hey, so today I want to show you the three mistakes that kill your reach on TikTok.",
        "Um, mistake number one: you start way too slow.",
        "Nobody waits ten seconds for you to get to the point.",
        "Mistake number two, uh, is dead air.",
        "And mistake number three: no captions.",
        "Fix these three things and your watch time goes up.",
        "Follow for part two.",
    ],
    "runs of short words": [
        "I am a man of my word and so on.",
        "It is ok to go.",
        "Go.",
    ],
    "German": [
        "Ich bin da, und du bist es auch.",
        "Fehler Nummer 1: Du fängst viel zu langsam an.",
        "Ähm, das war es.",
    ],
}


def v1_units(segments: list[dict]) -> list[dict]:
    from src.audio import AudioAnalyzer

    fake = types.SimpleNamespace(_transcription={"segments": segments}, _subtitles=[])
    AudioAnalyzer._build_subtitles_from_transcription(fake)
    return [{"text": s.text, "start": round(s.start, 3), "end": round(s.end, 3)} for s in fake._subtitles]


def doc_words(segments: list[dict]) -> list[dict]:
    raw = [w for s in segments for w in s["words"]]
    return edit_doc.number_words(edit_doc.words_from_transcript(raw))


def build() -> dict:
    out = []
    for name, sentences in CASES.items():
        segs = _segments(sentences)
        out.append({"name": name, "words": doc_words(segs), "units": v1_units(segs)})
    return {
        "comment": "v1 caption units (src/audio.py) and the doc words (backend/doc.py) of one "
                   "transcription; doc.ts captionSource must give these units for the unedited "
                   "doc. Generated by backend/tests/test_caption_units_vectors.py --write.",
        "vectors": out,
    }


def test_vectors_match_v1_and_the_doc():
    assert json.loads(VECTORS.read_text()) == build()


def test_v1_glues_short_words_and_drops_fillers():
    v = build()["vectors"]
    texts = [u["text"] for u in v[0]["units"]]
    assert "so today" in texts and "I want" in texts
    assert not any("uh," in t for t in texts)  # a filler sound: dropped
    assert [w["text"] for w in v[0]["words"] if w.get("hidden")] == ["uh,"]
    assert not any("Ähm" in u["text"] for u in v[2]["units"])


if __name__ == "__main__" and "--write" in sys.argv:
    VECTORS.write_text(json.dumps(build(), indent=1, ensure_ascii=False) + "\n")
    print(f"wrote {VECTORS}")
