/**
 * Bundles the caption layer CLI (web/src/lib/captions/node/render-layer.ts,
 * the editor's caption engine) into backend/captions/render_layer.mjs.
 *
 *   cd backend/captions && npm ci && node build.mjs
 *
 * Run by the Modal image build (backend/modal_render.py) and by the
 * tests' session fixture. @napi-rs/canvas (native) and harfbuzzjs (WASM)
 * stay external: they load from backend/captions/node_modules at run
 * time. The web's own fonts.json is inlined; the font files are read
 * from the fontsDir the backend passes (web/public/fonts/captions).
 */
import { build } from "esbuild";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

await build({
  entryPoints: [here("../../web/src/lib/captions/node/render-layer.ts")],
  outfile: here("./render_layer.mjs"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  external: ["@napi-rs/canvas", "harfbuzzjs"],
  legalComments: "none",
  logLevel: "warning",
  banner: { js: "// Generated by backend/captions/build.mjs from web/src/lib/captions — do not edit." },
});
console.log("render_layer.mjs built");
